<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="8.0.14" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.14" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.14" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Game.Common\Game.Common.csproj" />
    </ItemGroup>

</Project>
