<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Agent</RootNamespace>
    <AssemblyName>Agent</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CfrSolver.Datalayer\CfrSolver.Datalayer.csproj" />
    <ProjectReference Include="..\CfrSolver\CfrSolver.csproj" />
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Game\Game.csproj" />
    <ProjectReference Include="..\MarkItDown\MarkItDown.csproj" />
    <ProjectReference Include="..\PT\PT.csproj" />
    <ProjectReference Include="..\scr\scr.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="emulog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CfrSolver.Graphgen\" />
    <Folder Include="CfrSolver.Player\" />
  </ItemGroup>
</Project>