<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Game</RootNamespace>
    <AssemblyName>Game</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CfrSolver\CfrSolver.csproj" />
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Game.Presentation\Game.Presentation.csproj" />
    <ProjectReference Include="..\PT\PT.csproj" />
  </ItemGroup>
</Project>